"""vibetrace: prompt-to-code provenance tracking with security correlation.

This package's import path is shared by the Claude Code hook entrypoint
(python -m vibetrace.hook), which must start fast and never fail. Keep this
module stdlib-only and free of side effects.
"""

__version__ = "0.1.0"

# Bump when the SQLite DDL changes shape.
SCHEMA_VERSION = "1"

# Bump when feature definitions in features.py change, so exported datasets
# can be filtered/regenerated by extractor version (see `vibetrace rebuild`).
FEATURES_VERSION = "1"
